import type { CurrencyCode } from "../currency";
import type { Cents } from "../money";
import type { LoanDirection, RecurringFrequency, TransactionSource, TransactionType } from "../index";

// Full-data backup: everything a user owns, as one JSON file
// (GET /api/account/backup). Ids are the original ones and only serve to link
// records inside the file — importing gives every record a new id.
//
// FORMAT VERSIONING: bump BACKUP_VERSION whenever the shape changes, and add a
// step to the server's backup migrations (server/src/services/backup.service.ts)
// that upgrades the previous version, so older files keep importing.
export const BACKUP_FORMAT = "budget-app-backup";
export const BACKUP_VERSION = 1;

export interface BackupCategory {
  id: string;
  name: string;
  type: TransactionType;
  color: string;
  isDefault: boolean;
}

export interface BackupTransaction {
  id: string;
  categoryId: string;
  type: TransactionType;
  amountCents: Cents;
  description: string;
  date: string; // ISO timestamp
  source: TransactionSource;
  recurringId?: string; // generated by this recurring rule
  loanId?: string; // a loan's own transaction or one of its repayments
}

export interface BackupBudget {
  id: string;
  categoryId: string;
  limitCents: Cents;
  month: number;
  year: number;
}

export interface BackupRecurring {
  id: string;
  categoryId: string;
  type: TransactionType;
  amountCents: Cents;
  description: string;
  frequency: RecurringFrequency;
  interval: number;
  startDate: string;
  endDate?: string;
  lastGeneratedDate?: string;
  isActive: boolean;
}

export interface BackupRepayment {
  amountCents: Cents;
  date: string;
  note?: string;
  transactionId: string;
}

export interface BackupLoan {
  id: string;
  counterparty: string;
  direction: LoanDirection;
  principalCents: Cents;
  description: string;
  date: string;
  transactionId: string;
  writtenOff: boolean;
  repayments: BackupRepayment[];
}

export interface BackupFile {
  format: typeof BACKUP_FORMAT;
  version: number;
  exportedAt: string;
  settings: { name: string; currency: CurrencyCode };
  categories: BackupCategory[];
  transactions: BackupTransaction[];
  budgets: BackupBudget[];
  recurring: BackupRecurring[];
  loans: BackupLoan[];
}

export interface BackupSummary {
  version: number;
  exportedAt: string;
  currency: CurrencyCode;
  counts: { categories: number; transactions: number; budgets: number; recurring: number; loans: number; repayments: number };
  dateRange: { from: string; to: string } | null;
}

// POST /api/account/backup/preview — validates without importing.
export interface BackupPreviewResponse {
  summary: BackupSummary;
  // True when the account already has its own transactions, budgets,
  // recurring rules, loans or custom categories: importing then replaces
  // them, and needs `replaceExisting: true`.
  accountHasData: boolean;
}

export interface ImportBackupInput {
  backup: unknown;
  replaceExisting: boolean;
}

export interface ImportBackupResponse {
  summary: BackupSummary;
}
